export const LOAD_CONTACTS_ACTION_REQUEST = "LOAD_CONTACTS_ACTION_REQUEST";
export const LOAD_CONTACTS_ACTION_FAILURE = "LOAD_CONTACTS_ACTION_FAILURE";
export const LOAD_CONTACTS_ACTION_SUCCESS = "LOAD_CONTACTS_ACTION_SUCCESS";
export const SET_FAVORITES_CONTACTS_ACTION = "SET_FAVORITES_CONTACTS_ACTION";
export const GET_CONTACT_NAME_ACTION = "GET_CONTACT_NAME_ACTION";
export const SET_CURRENT_GROUP_ID_ACTION = "SET_CURRENT_GROUP_ID_ACTION";
export const UNSET_CURRENT_GROUP_ID_ACTION = "UNSET_CURRENT_GROUP_ID_ACTION";
export const FILTER_BY_CURRENT_GROUP_ID_ACTION =
  "FILTER_BY_CURRENT_GROUP_ID_ACTION";

export const LOAD_GROUP_CONTACT = "LOAD_GROUP_CONTACT";
export const GET_GROUP_CONTACT_ACTION = "GET_GROUP_CONTACT_ACTION";
